// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngkltltsvhxqehbrdnkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5na2x0bHRzdmh4cWVoYnJkbmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjQ4MzMsImV4cCI6MjA2NTkwMDgzM30.R0mufC78C2lLRYo0C40lKkOd9Hr7WSnnoLnYUFBPqrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);